// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFirstAzureWebApp.Models;

public partial class AddDate
{
    public int id { get; set; }

    public int mMovieId { get; set; }

    public string mTitle { get; set; }

    public DateOnly? mDateAdd { get; set; }

    public virtual Movie mMovie { get; set; }
}