// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFirstAzureWebApp.Models;

public partial class DateView
{
    public int id { get; set; }

    public int? mMovieId { get; set; }

    public string mTitle { get; set; }

    public int? mMinutes { get; set; }

    public string mLocation { get; set; }

    public DateTime? mViewingDate { get; set; }

    public int? mViewingYear { get; set; }

    public DateTime? mViewingMonth { get; set; }

    public virtual Movie mMovie { get; set; }
}