// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFirstAzureWebApp.Models;

public partial class Movie
{
    public int id { get; set; }

    public string mTitle { get; set; }

    public int mReleaseYear { get; set; }

    public int mMinutes { get; set; }

    public double? mIMDbRating { get; set; }

    public string mSeenit { get; set; }

    public string mLocation { get; set; }

    public string mDirector { get; set; }

    public string mMovieFiles { get; set; }

    public string mImdburl { get; set; }

    public string mTrailerURLs { get; set; }

    public string mGenre { get; set; }

    public string mPlot { get; set; }

    public string mImage { get; set; }

    public string mActors { get; set; }

    public string mRunningTime { get; set; }

    public string mSidrot { get; set; }

    public string mTag1 { get; set; }

    public string edb { get; set; }

    public DateTime? mLastModifies { get; set; }

    public virtual ICollection<AddDate> AddDate { get; set; } = new List<AddDate>();

    public virtual ICollection<DateView> DateView { get; set; } = new List<DateView>();
}