// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace MyFirstAzureWebApp.Models;

public partial class MOVIESContext : DbContext
{
    public MOVIESContext()
    {
    }

    public MOVIESContext(DbContextOptions<MOVIESContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AddDate> AddDate { get; set; }

    public virtual DbSet<DateView> DateView { get; set; }

    public virtual DbSet<Movie> Movie { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)

        => optionsBuilder.UseSqlServer("Data Source=asersqlserver.database.windows.net;Initial Catalog=MOVIES;Persist Security Info=True;User ID=aser58;Password=Aser311258!");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AddDate>(entity =>
        {
            entity.HasIndex(e => e.id, "IX_AddDate");

            entity.Property(e => e.mTitle)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.mMovie).WithMany(p => p.AddDate)
                .HasForeignKey(d => d.mMovieId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AddDate_Movie");
        });

        modelBuilder.Entity<DateView>(entity =>
        {
            entity.Property(e => e.mLocation).HasMaxLength(255);
            entity.Property(e => e.mTitle).HasMaxLength(255);
            entity.Property(e => e.mViewingDate).HasColumnType("datetime");
            entity.Property(e => e.mViewingMonth).HasColumnType("datetime");

            entity.HasOne(d => d.mMovie).WithMany(p => p.DateView)
                .HasForeignKey(d => d.mMovieId)
                .HasConstraintName("FK_DateView_Movie");
        });

        modelBuilder.Entity<Movie>(entity =>
        {
            entity.HasIndex(e => e.mTitle, "TitleUnique").IsUnique();

            entity.Property(e => e.edb).HasMaxLength(255);
            entity.Property(e => e.mDirector).HasMaxLength(255);
            entity.Property(e => e.mGenre).HasMaxLength(255);
            entity.Property(e => e.mImage).HasMaxLength(255);
            entity.Property(e => e.mImdburl).HasMaxLength(255);
            entity.Property(e => e.mLastModifies).HasColumnType("datetime");
            entity.Property(e => e.mLocation).HasMaxLength(255);
            entity.Property(e => e.mMovieFiles).HasMaxLength(255);
            entity.Property(e => e.mRunningTime).HasMaxLength(255);
            entity.Property(e => e.mSeenit).HasMaxLength(255);
            entity.Property(e => e.mSidrot).HasMaxLength(255);
            entity.Property(e => e.mTag1).HasMaxLength(255);
            entity.Property(e => e.mTitle)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.mTrailerURLs).HasMaxLength(255);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}